name: DummyDB CI

on:
  push:
    # Execute workflow when pushing in main
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    # Execute workflow when creating a pull request
    branches: [ "main" ]
  workflow_call: 
  

jobs:
  build-ubuntu:
    # OS where the workflow will run
    runs-on: ubuntu-latest

    # Permissions that the workflow has
    # permissions:
    #   contents: read
    #   issues: read
    #   pull-requests: read

    steps:
      # Clones the project and checkout
      - name: Configure (Checkout to latest version)
        uses: actions/checkout@v4

      # Install dependencies using apt-get
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake

      # Build the project 
      - name: Build with make
        run: make release

      # Run the tests
      - name: Runs tests
        run: make test
    
