name: DummyDB CI/CD

on:
  push:
    # Execute workflow when pushing in main
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    # Execute workflow when creating a pull request
    branches: [ "main" ]
  

jobs:
  build-ubuntu:
    # OS where the workflow will run
    runs-on: ubuntu-latest

    # Permissions that the workflow has
    # permissions:
    #   contents: read
    #   issues: read
    #   pull-requests: read

    steps:
      # Clones the project and checkout
      - name: Configure (Checkout to latest version)
        uses: actions/checkout@v4

      # Install dependencies using apt-get
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake  # add any libs you need

      # Build the project 
      - name: Build with make
        run: make release

  test-ubuntu:
    runs-on: ubuntu-latest
    needs: build-ubuntu

    steps:
      # Run the tests
      - name: Runs tests
        run: make test

  deploy-ubuntu:
    # TODO: Check action ref
    if: github.action_ref == 'tags'
    runs-on: ubuntu-latest
    needs: build-ubuntu

    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            "./build/main"
             "./LICENSE"
          if-no-files-found: error
    
