name: DummyDB CI

on:
  push:
    # Execute workflow when pushing in main
    branches: [ "main" ]
  pull_request:
    # Execute workflow when creating a pull request
    branches: [ "main" ]
  workflow_call: 
  

jobs:
  build-ubuntu:
    # OS where the workflow will run
    runs-on: ubuntu-latest

    # Permissions that the workflow has
    # permissions:
    #   contents: read
    #   issues: read
    #   pull-requests: read

    steps:
      # Clones the project and checkout
      - name: Configure (Checkout to latest version)
        uses: actions/checkout@v4

      # Install dependencies using apt-get
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake

      # Generate unique number version for artifact
      # https://www.codegenes.net/blog/how-to-version-build-artifacts-using-github-actions/
      - name: Generate unique version
        id: generate_version
        run: |
          # Get current timestamp (YYYYMMDDHHMMSS format, e.g., 20240520153045)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          # Combine run_id and timestamp (e.g., v123456789-20240520153045)
          VERSION="v${{ github.run_id }}-${TIMESTAMP}"
          # Store version in environment variable for later steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the project 
      - name: Build with make
        run: |
          make release
          echo "Built app version: ${{ env.VERSION }}"

      # Run the tests
      - name: Runs tests
        run: make test

      # Docker test
      - name: Runs tests
        run: docker build .

      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dummydb-build-${{ env.VERSION }}
          path: |
            ./build/main
            ./LICENSE
    
